name: plasticdive
description: Plastic Dive is a game where you dive into the ocean to collect plastic and save the marine life.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Game
  flame: ^1.16.0

  # Firebase
  firebase_core: ^2.25.5
  cloud_firestore: ^4.15.6

  # Audio
  flame_audio: ^2.10.0

  # Stacked Framework
  stacked: ^3.4.1+1
  stacked_services: ^1.4.0
  animations: ^2.0.11

  # Onboarding / How-to play
  introduction_screen: ^3.1.12

  # Preferences & Storage
  shared_preferences: ^2.2.2

  # Web metadata (SEO)
  meta_seo: ^3.0.9

  stacked_shared: any
  logging: ^1.2.0
dev_dependencies:
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  # Logo
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.1
  mockito: ^5.4.4
  stacked_generator: ^1.6.0

dependency_overrides:
  meta: ^1.12.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/audio/music/
    - assets/audio/sfx/
    - assets/images/
    - assets/images/how-to-play/
    - assets/images/icons/
    - assets/images/screens-backgrounds/
    - assets/images/parallax/
    - assets/images/parallax/surface/
    - assets/images/ui/
    - assets/images/players/
    - assets/images/garbages/
    - assets/images/animals/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: PixeloidSans
       fonts:
         - asset: assets/fonts/PixeloidSans.ttf
         - asset: assets/fonts/PixeloidSans-Bold.ttf
           weight: 700
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
